### ISSUE TITLE
volttron-7-preview SQLHistorian does not work in Python 3

### ISSUE THREAD

**Issue by rjdkolb** [VOLTTRON/volttron#2177]
### Description of Issue
The PostgreSQL historian has an issue with Python 3 and the DBDriver.
The DBDriver cursor no longer has a **.next()** and **.fetchone()** should be used.

This is an example where both inserts work in Python 2, but only the "**.fetchone()**" method works in Python 3. i.e. using "**.fetchone()**" will not break Python 2.

```
import psycopg2
from psycopg2.sql import Identifier, SQL

from datetime import datetime

dbname = 'db'
user = 'testuser'
password = 'somepasswordnothere'

host = 'localhost'

conn = psycopg2.connect(dbname=dbname, user=user, password=password, host=host)
topics_table = 'topics'

with conn.cursor() as cursor:
    print('About to insert and get Primary key back with fetchone()[0]')
    random_string = datetime.today().strftime('%s') + '1'
    insert_topic_query = SQL('INSERT INTO {} (topic_name) VALUES (%(topic)s) RETURNING topic_id').format(Identifier(topics_table))
    cursor.execute(insert_topic_query, {'topic': random_string})
    print(cursor.fetchone()[0])
    print('DONE with insert and get Primary key back with fetchone()[0]')

with conn.cursor() as cursor:
    print('About to insert and get Primary key back with next()[0]')
    random_string = datetime.today().strftime('%s')  + '2'
    insert_topic_query = SQL('INSERT INTO {} (topic_name) VALUES (%(topic)s) RETURNING topic_id').format(Identifier(topics_table))
    cursor.execute(insert_topic_query, {'topic': random_string})
    try:
        print(cursor.next()[0])
        print('DONE with insert and get Primary key back with next()[0]')
    except Exception as e:
        print('Failed with insert and get Primary key back with next()[0] {e}'.format(e.message))
```

docker-compose.xml:

```
version: "3"
services:
  db:
    image: timescale/timescaledb:latest-pg11
    volumes:
      - postgresql-data:/var/lib/postgresql
    container_name: postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=somepasswordnothere
      - POSTGRES_DB=db

volumes:
  postgresql-data:
```

So this should change in "postgresqlfuncts.py"

```
    def insert_topic(self, topic):
        with self.cursor() as cursor:
            cursor.execute(self.insert_topic_query(), {'topic': topic})
            return cursor.fetchone()[0]

    def insert_agg_topic(self, topic, agg_type, agg_time_period):
        with self.cursor() as cursor:
            cursor.execute(self.insert_agg_topic_stmt(),
                           (topic, agg_type, agg_time_period))
            return cursor.fetchone()[0]
```
The same code is in "redshiftfuncts.py"

### Affected Version
volttron-7-preview

### Steps to Reproduce

Start up SQL historian and write a new topic
